### PR TITLE
Don't leak a connection when opening fails

### LINKED ISSUE #488: `vroom` does not close failed connections
This is more or less the same issue as in https://github.com/tidyverse/readr/issues/1050 

vroom doesn't close connections that failed, e.g. a URL with a typo.

``` r
# Correct URL
to_load <- "https://cloud.r-project.org/CRAN_mirrors.csv"
mirrors <- vroom::vroom(to_load, show_col_types = FALSE)
showConnections(all = TRUE)
#>   description class            mode text   isopen   can read can write
#> 0 "stdin"     "terminal"       "r"  "text" "opened" "yes"    "no"     
#> 1 "stdout"    "terminal"       "w"  "text" "opened" "no"     "yes"    
#> 2 "stderr"    "terminal"       "w"  "text" "opened" "no"     "yes"    
#> 3 "output"    "textConnection" "wr" "text" "opened" "no"     "yes"

# URL with typo
to_load_typo <- "https://cloud.r-project.org/CRAN_mirrorsZ.csv"
mirrors <- vroom::vroom(to_load_typo, show_col_types = FALSE)
#> Error in open.connection(structure(4L, class = c("curl", "connection"), conn_id = <pointer: 0x153>), : HTTP error 404.
showConnections(all = TRUE)
#>   description                                     class            mode text  
#> 0 "stdin"                                         "terminal"       "r"  "text"
#> 1 "stdout"                                        "terminal"       "w"  "text"
#> 2 "stderr"                                        "terminal"       "w"  "text"
#> 3 "output"                                        "textConnection" "wr" "text"
#> 4 "https://cloud.r-project.org/CRAN_mirrorsZ.csv" "curl"           "rb" "text"
#>   isopen   can read can write
#> 0 "opened" "yes"    "no"     
#> 1 "opened" "no"     "yes"    
#> 2 "opened" "no"     "yes"    
#> 3 "opened" "no"     "yes"    
#> 4 "closed" "yes"    "no"
```

<sup>Created on 2023-02-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23)
#>  os       macOS Ventura 13.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language en
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Berlin
#>  date     2023-02-19
#>  pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  bit           4.0.5      2022-11-15 [1] CRAN (R 4.2.0)
#>  bit64         4.0.5      2020-08-30 [1] CRAN (R 4.2.0)
#>  cli           3.6.0      2023-01-09 [1] CRAN (R 4.2.0)
#>  crayon        1.5.2      2022-09-29 [1] CRAN (R 4.2.0)
#>  curl          5.0.0      2023-01-12 [1] CRAN (R 4.2.0)
#>  digest        0.6.31     2022-12-11 [1] CRAN (R 4.2.0)
#>  evaluate      0.20       2023-01-17 [1] CRAN (R 4.2.0)
#>  fansi         1.0.4      2023-01-22 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.6.1      2023-02-06 [1] CRAN (R 4.2.0)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.4      2022-12-07 [1] CRAN (R 4.2.0)
#>  knitr         1.42       2023-01-25 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.8.1      2022-08-19 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         1.0.1      2023-01-10 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.2     2022-11-11 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2      2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.6      2022-09-24 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.20       2023-01-19 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
#>  styler        1.9.0      2023-01-15 [1] CRAN (R 4.2.0)
#>  tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.0)
#>  tidyselect    1.2.0.9000 2022-11-02 [1] Github (tidyverse/tidyselect@b449033)
#>  tzdb          0.3.0      2022-03-28 [1] CRAN (R 4.2.0)
#>  utf8          1.2.3      2023-01-31 [1] CRAN (R 4.2.0)
#>  vctrs         0.5.2      2023-01-23 [1] CRAN (R 4.2.0)
#>  vroom         1.6.1      2023-01-22 [1] CRAN (R 4.2.0)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.37       2023-01-31 [1] CRAN (R 4.2.0)
#>  yaml          2.3.7      2023-01-23 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

If we repeat this a couple of times, R warns about closing unused connections like this 

```
Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (https://cloud.r-project.org/CRAN_mirrorsZ.csv)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 3 (https://cloud.r-project.org/CRAN_mirrorsZ.csv)
3: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 4 (https://cloud.r-project.org/CRAN_mirrorsZ.csv)
```

### PR DESCRIPTION
**Pull request by jennybc**
Fixes #488

### CODE REVIEW

File: R/path.R [hunk 1]
```diff
@@ -113,7 +116,7 @@ standardise_connection <- function(con) {
   con
 }
 
-standardise_one_path <- function(path, write = FALSE, call = caller_env()) {
+connection_or_filepath <- function(path, write = FALSE, call = caller_env()) {
```
Comment (jennybc) [inline R/path.R:119]: From its name, it's easy to expect that `standardise_path()` is (approximately) `map(several_inputs, standardise_one_path)` and that is just really not the case.

I'm renaming standardise_one_path() to better reflect what it does. This is just something I did while getting know this area of the codebase.

**Comment by jennybc** [comment]
@DavisVaughan I'm just looking for a basic sanity check and confirmation that I'm not overlooking some nicer solution. I contemplated and even tried various other strategies and this seems to be best AFAICT.

File: R/path.R [hunk 2]
```diff
@@ -225,6 +228,23 @@ standardise_one_path <- function(path, write = FALSE, call = caller_env()) {
...
+# good options for arranging the necessary cleanup.
+open_safely <- function(con, open_mode = "rb") {
+  tryCatch(
+    open(con, open_mode),
+    error = function(e) {
+      # The failed connection is already "closed", so this attempt to close() it
+      # is really about removing it from R's connection table.
+      try(close(con), silent = TRUE)
+
+      stop(conditionMessage(e), call. = FALSE)
```
Comment (jennybc) [inline R/path.R:243]: I am using `cli::cli_abort()` elsewhere in vroom's R code. But I have no ambition to add a class, wire the calling function through, or prettify the error message (which I don't control) and think this is rare enough that I feel content with just rethrowing.

File: tests/testthat/test-connection.R [hunk 3]
```diff
@@ -85,3 +85,45 @@ test_that("vroom works with windows newlines and a connection size that lies dir
   })
   expect_equal(x[[1]], c("a", "e"))
 })
+
```
Comment (jennybc) [inline tests/testthat/test-connection.R:88]: Both of the new tests do fail on `main` FWIW.

There are likely other situations where opening the connection fails and I think it's an improvement that we're handling that better now. The second test is an example of another reason for failure, beyond the nonexistent URL presented in the motivating issue.

File: tests/testthat/test-connection.R [hunk 4]
```diff
@@ -85,3 +85,45 @@ test_that("vroom works with windows newlines and a connection size that lies dir
...
+    ),
+    "cannot open"
+  )
+
+  connections_after <- showConnections(all = TRUE)
+  expect_equal(nrow(connections_before), nrow(connections_after))
+})
+
+test_that("vroom_fwf() doesn't leak a connection when opening fails (permission denied)", {
+  skip_on_os("windows")
```
Comment (jennybc) [inline tests/testthat/test-connection.R:109]: Permissions are different enough on Windows that I'd rather just skip there.

**Review by DavisVaughan — APPROVED** [review]
Discussed over zoom, seems like the best option!
