### PR TITLE
Stop inheriting docs from readr

### LINKED ISSUE #515: Don't inherit docs from readr
This task was started but not finished in #461. There are still several instances of `#' @inheritParams readr::some_function`. Something I am currently puzzling over is why readr's namespace gets loaded during `R CMD check` for vroom (not a huge deal, but still seems incorrect, and can lead to test failure in certain contexts) and it appears to be happening when updating vroom's docs. Part of the ongoing task of rationalizing the relationship between readr and vroom.

### PR DESCRIPTION
**Pull request by jennybc**
Closes #515

This motivated lots of tweaks, both in docs I copied over and in docs that were already here in vroom.

### CODE REVIEW

File: R/col_types.R [hunk 1]
```diff
@@ -823,8 +831,67 @@ col_factor <- function(
   )
 }
 
-#' @inheritParams readr::col_datetime
 #' @rdname cols
+#' @param format A format specification. If set to "":
```
Comment (jennybc) [inline R/col_types.R:835]: This content got an upgrade during/after the transplant procedure.

File: R/vroom.R [hunk 2]
```diff
@@ -101,21 +102,23 @@
...
+#'   `NULL` (the default), they are shown only if an explicit specification is
+#'   not given in `col_types`, i.e. if the types have been guessed.
 #' @param .name_repair Handling of column names. The default behaviour is to
 #'   ensure column names are `"unique"`. Various repair strategies are
 #'   supported:
 #'   * `"minimal"`: No name repair or checks, beyond basic existence of names.
 #'   * `"unique"` (default value): Make sure names are unique and not empty.
-#'   * `"check_unique"`: no name repair, but check they are `unique`.
+#'   * `"check_unique"`: No name repair, but check they are `unique`.
+#'   * `"unique_quiet"`: Repair with the `unique` strategy, quietly.
```
Comment (jennybc) [inline R/vroom.R:118]: vroom previously wasn't mentioning `"unique_quiet"` and `"universal_quiet"`.
